### ISSUE TITLE
how to flip the card to show back side data of each card

### ISSUE THREAD

**Issue by nick70007** [zhxnlai/ZLSwipeableViewSwift#137]

**Comment by nick70007** [comment]
i have used the library and was able to achieve the swiping feature and the cards are showing behind one another. Now i need to flip the card and show the content inside it, in my case i have spanish word showing in the front card when the app runs, but when i  flip the card it should show the english word of spanish meaning

**Comment by AndrewSB** [comment]
Hey Nick,

That would be something out of scope for this library — it aims to be a simple container for the cards. What’s in the cards themselves is up to you to build.
It shouldn’t be hard to make the cards flip — you can use a tap gesture recognizer to sense when the card is tapped, after which you can set an animation to flip the card. Take a look at the `UIView.transition` API, as explored in this blog post https://medium.com/@lawrey/creating-a-flip-card-animation-with-uicollectionviewcell-swift-3-0-98bc96317fee

I’m going to close this because it’s off topic for the container, but please feel free to circle back if there’s something you need this library to do to better accomplish your goal — a pull request to enable the functionality you need would be super 😉

**Comment by nick70007** [comment]
I have tried with tap gesture also but still no luck. Infact i have tried
many ways
