### ISSUE TITLE
Example app crash: Can't form Range with end < start

### ISSUE THREAD

**Issue by drinkius** [zhxnlai/ZLSwipeableViewSwift#49]
In History & Previous View implementations if I try to Rewind or Load Previous - the app crashes with "fatal error: Can't form Range with end < start". Don't need this functionality for now but can look into it myself a bit later when my schedule is less hectic

Xcode: Version 7.3
Device: iPhone 5s + any Simulator instance

**Comment by AndrewSB** [comment]
Thanks for taking a look @drinkius, let me know if there's anything I can do to assist!

**Comment by krisanthony** [comment]
Guys it looks like the issue is the back-most card is not being removed when the rewinded card is being inserted, leaving too many cards and breaking the `loadViews` method.

So simply add `remove(activeViews().last!)` before the `insert` call in the `rewind` method.

Fixed it for me.

Added a pull request https://github.com/zhxnlai/ZLSwipeableViewSwift/pull/53

**Comment by AndrewSB** [comment]
Thanks @krisanthony!
